# ENCODER_MAP_ENABLE = yes
ENCODER_ENABLE = yes

BOOTLOADER = atmel-dfu
RGB_MATRIX_ENABLE = yes

# space saving
LTO_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
